default_language_version:
  python: python3
repos:

-   repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml

-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
    -   id: nbqa-black
        exclude: ^docs/
    -   id: nbqa-isort
        exclude: ^docs/
    -   id: nbqa-ruff
        exclude: ^docs/
    -   id: nbqa-mypy
        exclude: ^docs/

-   repo: https://github.com/MarcoGorelli/cython-lint
    rev: v0.15.0
    hooks:
    -   id: cython-lint
    -   id: double-quote-cython-strings

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        exclude: ^docs/

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        exclude: ^docs/

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.270'
    hooks:
    -   id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        exclude: ^docs/

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5  # Use the latest version of pylint from the mirror
    hooks:
    -   id: pylint
        args: ['--rcfile=.pylintrc']  # Customize pylint arguments if needed


